[Manager]
DefaultTimeoutStartSec=10s
DefaultTimeoutStopSec=10s
DefaultRestartSec=100ms
ManagerEnvironment=MALLOC_ARENA_MAX=2
CPUAffinity=numa
DefaultCPUAccounting=no
DefaultMemoryAccounting=no
DefaultIOAccounting=no
DefaultTasksAccounting=yes
DefaultTasksMax=35%
