---
mountOptions:
    default: defaults,noatime,nodiratime
    btrfs: defaults,noatime,nodiratime,compress=zstd:1
ssdExtraMountOptions:
    ext4: discard,noatime
    xfs: discard,noatime
    btrfs: discard,noatime,compress=zstd:1
crypttabOptions: luks,discard,keyscript=/bin/cat

