---
backend: apt
operations:
  - remove:
      - 'live-boot'
      - 'live-boot-doc'
      - 'live-boot-initramfs-tools'
      - 'live-config'
      - 'live-config-doc'
      - 'live-config-systemd'
      - 'live-tools'
      - 'live-task-localisation'
      - 'live-task-localisation-desktop'
      - 'live-task-recommended'
      - 'live-task-base'
      - 'calamares'
      - 'calamares-settings-debian'
      - 'squashfs-tools'
      - 'memtester'
      - 'user-setup'
      - 'rsync'
      - 'acpica-tools'
      - 'cpuid'
      - 'edid-decode'
      - 'extrepo'
      - 'extrepo-offline-data'
      - 'hwinfo'
      - 'hw-probe'
      - 'time'





