[General]
__userfile__=true
icon_follow_color_scheme=false
icon_theme=breeze-dark
palette_override=true
single_click_activate=false
theme=Dark Breeze by Nudnik
tool_bar_icon_size=24
tool_button_style=ToolButtonIconOnly
wallpaper_override=false

[Icons]
colorize_icons=false

[Palette]
base_color=#1a1d1f
highlight_color=#0080aa
highlighted_text_color=#ffffff
link_color=#0080aa
link_visited_color=#9b59b6
text_color=#eff0f1
tooltip_base_color=#2a2e32
tooltip_text_color=#eff0f1
window_color=#2a2e32
window_text_color=#eff0f1
button_color=#2a2e32
button_text_color=#eff0f1
mid_color=#1a1d1f
dark_color=#1a1d1f
midlight_color=#31363b
shadow_color=#111315
bright_text_color=#eff0f1
disabled_text_color=#6d7a86
disabled_button_text_color=#6d7a86

[Qt]
font="Inter,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
style=kvantum
