[General]
panels=panel1

[panel1]
alignment=0
animationDuration=0
autoHide=false
iconSize=22
lockPanel=false
opacity=100
panelSize=36
plugins=fancymenu, desktopswitch, taskbar, statusnotifier, tray, volume, worldclock, showdesktop
position=Bottom
rowCount=1
showBorder=true
iconTheme=breeze-dark
colorizeIcons=false

[panel1/fancymenu]
alignment=-1
icon=/usr/share/spark/spark-icon.png
type=fancymenu

[panel1/desktopswitch]
type=desktopswitch

[panel1/taskbar]
buttonWidth=180
closeOnMiddleClick=true
groupingEnabled=false
type=taskbar

[panel1/worldclock]
alignment=1
type=worldclock

[panel1/volume]
type=volume

[panel1/tray]
type=tray

[panel1/statusnotifier]
type=statusnotifier

[panel1/showdesktop]
type=showdesktop
