shadow-exclude = [
  "class_g = 'calamares'"
];

fade-exclude = [
  "class_g = 'calamares'"
];

focus-exclude = [
  "class_g = 'calamares'"
];

blur-background-exclude = [
  "class_g = 'calamares'"
];

opacity-rule = [
  "100:class_g = 'calamares'"
];
