[Login]
KillUserProcesses=no
KillOnlyUsers=
KillExcludeUsers=root
InhibitDelayMaxSec=5
HandlePowerKey=poweroff
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=ignore
PowerKeyIgnoreInhibited=no
SuspendKeyIgnoreInhibited=no
IdleAction=ignore
